### ISSUE TITLE
Provide package not available

### ISSUE THREAD

**Issue by kkadiyam** [piizei/terraform-container-apps#1]
Hello, When i am trying to use this azapi provider it doesn't work, getting below error, Anything you can help here ?

Initializing Terraform Cloud...

Initializing provider plugins...
- Finding hashicorp/azurerm versions matching ">= 2.0.0, ~> 2.0, >= 2.70.0"...
- Finding latest version of hashicorp/namep...
- Finding latest version of hashicorp/null...
- Finding latest version of hashicorp/local...
- Finding latest version of azure/azapi...
- Installing hashicorp/azurerm v2.99.0...
- Installed hashicorp/azurerm v2.99.0 (signed by HashiCorp)
- Installing hashicorp/null v3.1.1...
- Installed hashicorp/null v3.1.1 (signed by HashiCorp)
- Installing hashicorp/local v2.2.2...
- Installed hashicorp/local v2.2.2 (signed by HashiCorp)
- Installing azure/azapi v0.1.1...
- Installed azure/azapi v0.1.1 (signed by a HashiCorp partner, key ID 

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider
│ hashicorp/namep: provider registry registry.terraform.io does not have a
│ provider named registry.terraform.io/hashicorp/namep
│ 
│ All modules should specify their required_providers so that external
│ consumers will get the correct providers when using a module. To see which
│ modules are currently depending on hashicorp/namep, run the following
│ command:
│     terraform provider

**Comment by sharebear** [comment]
Sounds like you've copied only part of the code from this repo. You're missing the provider requirement that tells terraform where to find the namep provider https://github.com/piizei/terraform-container-apps/blob/main/terraform/versions.tf#L7

(p.s. I'd delete your question in the azurerm issue as it doesn't relate to the issue being discussed at all)

**Comment by kkadiyam** [comment]
Thanks @sharebear , I was able to fix that error, Running into below one now, I never user parent_id is this a bicep requirement ?

I passed parent_id as module.resource_group.resource_group.id, but getting below error, Can we not use modules here ?

Error: parent_id is invalid, expect id of resource whose scope is [ResourceGroup], but got scope Unknown
with azapi_resource.container_app_environment
on main.tf line 85, in resource "azapi_resource" "container_app_environment":
resource "azapi_resource" "container_app_environment" {

**Comment by kkadiyam** [comment]
I also tried to use  namep provider, Not sure what this provider is, but, getting below error if use it , I did commented out all data resources to remove the need of namep provider.

 Provider registry.terraform.io/jason-johnson/namep v1.0.4 does not have a package available for your current platform, darwin_arm64.

**Comment by sharebear** [comment]
Without knowing what your `resource_group` module does it would be hard to know. I would guess that id output isn't what you think it is.

**Comment by sharebear** [comment]
> I also tried to use namep provider, Not sure what this provider is

The documentation of the module is quite clear https://registry.terraform.io/providers/jason-johnson/namep/latest/docs it's just a utility to help format consistent names.

> but, getting below error if use it , I did commented out all data resources to remove the need of namep provider.
> 
> Provider registry.terraform.io/jason-johnson/namep v1.0.4 does not have a package available for your current platform, darwin_arm64.

You have one of those fancy new M1 macs and the provider hasn't been built for that architecture. If you want to use it your best bet is to open an issue against the namep github repository, but it's only a convenience, probably easiest to leave it out.

**Comment by kkadiyam** [comment]
Thanks @sharebear  I am able to fix this issue now.

Sorry, this might be a dumb question, As terraform is not available for container apps yet, how do we know which name to use for agape_resource ?, Like how you have "azapi_resource" "container_app" or "azapi_resource" "container_app_environment" , Why not it is containerapp (no dash) ?.

Also, Which arguments  to pass in per each resource ? (I assume it is ARM wrapped in terraform ?)

**Comment by sharebear** [comment]
> Thanks @sharebear I am able to fix this issue now.
> 
> Sorry, this might be a dumb question, As terraform is not available for container apps yet, how do we know which name to use for agape_resource ?, Like how you have "azapi_resource" "container_app" or "azapi_resource" "container_app_environment" , Why not it is containerapp (no dash) ?.

From the terraform documentation: https://www.terraform.io/language/resources/syntax

> A resource block declares a resource of a given type ("aws_instance") with a given local name ("web"). The name is used to refer to this resource from elsewhere in the same Terraform module, but has no significance outside that module's scope.
> 
> The resource type and name together serve as an identifier for a given resource and so must be unique within a module.

In short, it's just a local name that you decide for that instance of the resource. It has no meaning other than to yourself or whoever is reading your code.

> Also, Which arguments to pass in per each resource ? (I assume it is ARM wrapped in terraform ?)

Yes the AzAPI is just a thin wrapper around the ARM Rest API

I believe that this is the canonical source of documentation for ARM APIs in general https://docs.microsoft.com/en-us/azure/templates/ so the docs for the container apps are here https://docs.microsoft.com/en-us/azure/templates/microsoft.app/containerapps?tabs=json

**Comment by kkadiyam** [comment]
Thank You very much for your help!
https://docs.microsoft.com/en-us/azure/templates/microsoft.app/2022-01-01-preview/managedenvironments?tabs=bicep

**Comment by ms-henglu** [comment]
Hi @sharebear , @kkadiyam ,

So glad that you've tried with `azapi` provider! There's a [vscode extension](https://marketplace.visualstudio.com/items?itemName=azapi-vscode.azapi) for `azapi` provider which provides a rich authoring experience, and no need to look up the documents.

**Comment by piizei** [comment]
> I also tried to use namep provider, Not sure what this provider is, but, getting below error if use it , I did commented out all data resources to remove the need of namep provider.
> 
> Provider registry.terraform.io/jason-johnson/namep v1.0.4 does not have a package available for your current platform, darwin_arm64.

This is why I originally created the dev-container as I use M1 myself. I created issue for Jason about this: https://github.com/jason-johnson/terraform-provider-namep/issues/20

**Comment by piizei** [comment]
> This is why I originally created the dev-container as I use M1 myself. I created issue for Jason about this: [jason-johnson/terraform-provider-namep#20](https://github.com/jason-johnson/terraform-provider-namep/issues/20)

1.0.5 of namep was just released and I upgraded the versions.tf, Apple M1 / darwin_arm64 seems to work now.
