### ISSUE TITLE
Registry addition to the capp

### ISSUE THREAD

**Issue by kkadiyam** [piizei/terraform-container-apps#2]
Hi @piizei @ms-henglu Any idea how to add container registry details here ?, I tried multiple ways to add the details, but running into  below errors. 

Sorry, I do not find much of help out, So requesting your input here. Thanks!

Code: 

      configuration = {
        secrets : [
          {
            name : containerRegistryPasswordRef
            value : "ABC"
          }
        ]
        registries : [
          {
            server : containerRegistry
            username : containerRegistryUsername
            passwordSecretRef : containerRegistryPasswordRef
          }
        ]

Error: Error: Invalid reference
│ 
│   on container-app.tf line 41, in resource "azapi_resource" "container_app":
│   41:             name : containerRegistryPasswordRef
│ 
│ A reference to a resource type must be followed by at least one attribute
│ access, specifying the resource name.
╵
╷
│ Error: Invalid reference
│ 
│   on container-app.tf line 53, in resource "azapi_resource" "container_app":
│   53:             passwordSecretRef : containerRegistryPasswordRef

Even tried harcoding the ACR details in the registry block then getting below 400 error.

 RESPONSE 400: 400 Bad Request
│ ERROR CODE: ContainerAppRegistriesPasswordSecretRefNotFound

**Comment by piizei** [comment]
Hi @kkadiyam,
For me it looks like it's a bug in Container Instances, as the ARM payload is failing even with rest client. I will create an issue to their repo.

**Comment by piizei** [comment]
Issue https://github.com/microsoft/azure-container-apps/issues/212

**Comment by piizei** [comment]
This seems to work now, I changed the example to use private registry.
